-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Asiakas CASCADE;
-- DROP TABLE IF EXISTS Seurantalista CASCADE;
DROP TABLE IF EXISTS Esite CASCADE;
DROP TABLE IF EXISTS Tarjous CASCADE;
DROP TABLE IF EXISTS Tuoteluokka CASCADE;
DROP TABLE IF EXISTS EsitteenTuoteluokka CASCADE;